# Generated by Django 3.1.5 on 2021-03-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0003_auto_20210302_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_place',
            name='name',
        ),
        migrations.AddField(
            model_name='user_place',
            name='first_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='user_place',
            name='last_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='user_place',
            name='middle_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
