# Generated by Django 3.1.5 on 2021-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0004_auto_20210302_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('C', 'Cemetery'), ('CO', 'Columbarium')], max_length=2)),
                ('blk', models.CharField(max_length=3)),
                ('street', models.CharField(max_length=12)),
                ('lot', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='user_place',
            name='first_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='user_place',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='user_place',
            name='middle_name',
            field=models.CharField(max_length=60),
        ),
    ]
