# Generated by Django 3.1.5 on 2021-03-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0005_auto_20210302_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdata',
            name='place',
            field=models.CharField(default='', max_length=60),
        ),
    ]
