# Generated by Django 3.1.5 on 2021-03-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0006_masterdata_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='place',
            field=models.CharField(max_length=60),
        ),
    ]
