# Generated by Django 3.1.5 on 2021-03-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0009_auto_20210302_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_place',
            name='blk',
        ),
        migrations.RemoveField(
            model_name='user_place',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user_place',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_place',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_place',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='user_place',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='user_place',
            name='street',
        ),
    ]
