# Generated by Django 3.1.5 on 2021-03-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0010_auto_20210303_1922'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masterdata',
            table='master_data',
        ),
    ]
