# Generated by Django 3.1.5 on 2021-03-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0011_auto_20210303_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData_Revised',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('C', 'Cemetery'), ('CO', 'Columbarium')], max_length=2)),
                ('blk', models.CharField(max_length=3)),
                ('street', models.CharField(max_length=12)),
                ('lot', models.CharField(max_length=3)),
            ],
        ),
    ]
