# Generated by Django 3.1.5 on 2021-03-03 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0012_masterdata_revised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata_revised',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user_place',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='lapida_app.masterdata_revised', to_field='uid'),
        ),
    ]
