# Generated by Django 3.1.5 on 2021-03-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0013_auto_20210303_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterData',
        ),
    ]
