# Generated by Django 3.1.5 on 2021-03-04 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0014_delete_masterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Returned'), ('C', 'Completed'), ('Pa', 'Paid'), ('O', 'Ongoing')], max_length=2)),
                ('price', models.CharField(max_length=15)),
                ('services', models.CharField(max_length=15)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('profile_dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapida_app.user_place')),
            ],
        ),
    ]
