# Generated by Django 3.1.5 on 2021-03-04 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lapida_app', '0015_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cemetery', models.CharField(choices=[('MN', 'Manila North'), ('MS', 'Manila South'), ('L', 'La Loma'), ('MC', 'Manila Chinese')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Caretaker_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapida_app.caretaker')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapida_app.order_user')),
            ],
        ),
    ]
