# Generated by Django 3.1.5 on 2021-03-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0018_auto_20210305_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_user',
            name='services',
            field=models.CharField(max_length=150),
        ),
    ]
