# Generated by Django 3.1.5 on 2021-03-06 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0019_auto_20210305_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_user',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
