# Generated by Django 3.1.5 on 2021-03-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0020_order_user_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_user',
            name='note',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='order_user',
            name='services',
            field=models.CharField(max_length=200),
        ),
    ]
