# Generated by Django 3.1.5 on 2021-03-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0021_auto_20210306_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_user',
            name='note',
            field=models.CharField(max_length=180),
        ),
    ]
