# Generated by Django 3.1.5 on 2021-03-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0025_order_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretaker',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
