# Generated by Django 3.1.5 on 2021-03-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0026_auto_20210311_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
