# Generated by Django 3.1.5 on 2021-03-11 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0028_auto_20210311_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdata_revised',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
