# Generated by Django 3.1.5 on 2021-03-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0030_auto_20210311_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata_revised',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
    ]
