# Generated by Django 3.1.5 on 2021-03-13 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0031_auto_20210313_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_place',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapida_app.masterdata_revised'),
        ),
    ]
