# Generated by Django 3.1.5 on 2021-06-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lapida_app', '0036_auto_20210615_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
