# Generated by Django 3.1.6 on 2021-02-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caretakers',
            new_name='Caretaker',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
